# Generated by Django 3.0.8 on 2020-07-02 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('entered', models.DateField()),
                ('vaccination', models.BooleanField()),
                ('cage_num', models.CharField(max_length=16)),
            ],
        ),
    ]
