# Generated by Django 3.0.8 on 2020-07-02 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAnimal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=128)),
                ('breed', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.Passport')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('abstractanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.AbstractAnimal')),
            ],
            bases=('animals.abstractanimal',),
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('abstractanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.AbstractAnimal')),
                ('litter_box', models.BooleanField()),
                ('color', models.CharField(max_length=32)),
                ('fur', models.CharField(choices=[('L', 'Long'), ('S', 'Short'), ('H', 'Hairless')], default='S', max_length=1)),
            ],
            bases=('animals.abstractanimal',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('abstractanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.AbstractAnimal')),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default='M', max_length=1)),
            ],
            bases=('animals.abstractanimal',),
        ),
    ]
